/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-4.6-sonnet-low",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-medium",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-high",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-max",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-low-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-high-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-max-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-gpt-5.3-codex",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "gpt-5.3-codex",
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex-latest",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex-5.3",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-low",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-low-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-high",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-high-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultRunModelId: "claude-opus-4-7-thinking-xhigh",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh",
    wireId: "claude-opus-4-7-thinking-xhigh",
    displayName: "Claude Opus 4.7 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    runModelId: "claude-opus-4-7-thinking-xhigh",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4.7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4-7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-low",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-low-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-medium",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-medium-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-high",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-high-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-xhigh",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-xhigh-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-max",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-max-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-high",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-high-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "gpt-5.4-medium",
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-medium",
    wireId: "gpt-5.4-medium",
    displayName: "GPT-5.4 Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    runModelId: "gpt-5.4-medium",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-none",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-none-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-low",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-low-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-medium-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-high",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-high-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-xhigh",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-xhigh-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultRunModelId: "claude-4.6-opus-high-thinking",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-high-thinking",
    wireId: "claude-4.6-opus-high-thinking",
    displayName: "Claude Opus 4.6 Thinking Context 200k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-opus-4-6",
    runModelId: "claude-4.6-opus-high-thinking",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-opus-4.6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-opus-4-6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-low",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-medium",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-high",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-max",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-low-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-medium-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-max-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
]
