/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-7-thinking-high-fast",
    wireId: "claude-opus-4-7-thinking-high-fast",
    displayName: "Opus 4.7 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh",
    wireId: "claude-opus-4-7-thinking-xhigh",
    displayName: "Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh-fast",
    wireId: "claude-opus-4-7-thinking-xhigh-fast",
    displayName: "Opus 4.7 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max",
    wireId: "claude-opus-4-7-thinking-max",
    displayName: "Opus 4.7 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max-fast",
    wireId: "claude-opus-4-7-thinking-max-fast",
    displayName: "Opus 4.7 Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-low",
    wireId: "gpt-5.4-low",
    displayName: "GPT-5.4 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-medium",
    wireId: "gpt-5.4-medium",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-medium-fast",
    wireId: "gpt-5.4-medium-fast",
    displayName: "GPT-5.4 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-high",
    wireId: "gpt-5.4-high",
    displayName: "GPT-5.4 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-high-fast",
    wireId: "gpt-5.4-high-fast",
    displayName: "GPT-5.4 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-xhigh",
    wireId: "gpt-5.4-xhigh",
    displayName: "GPT-5.4 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-xhigh-fast",
    wireId: "gpt-5.4-xhigh-fast",
    displayName: "GPT-5.4 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-opus-high",
    wireId: "claude-4.6-opus-high",
    displayName: "Opus 4.6",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-opus-max",
    wireId: "claude-4.6-opus-max",
    displayName: "Opus 4.6 Max",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-opus-high-thinking",
    wireId: "claude-4.6-opus-high-thinking",
    displayName: "Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-opus-max-thinking",
    wireId: "claude-4.6-opus-max-thinking",
    displayName: "Opus 4.6 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-opus-high",
    wireId: "claude-4.5-opus-high",
    displayName: "Opus 4.5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-opus-high-thinking",
    wireId: "claude-4.5-opus-high-thinking",
    displayName: "Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-low",
    wireId: "gpt-5.2-low",
    displayName: "GPT-5.2 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-low-fast",
    wireId: "gpt-5.2-low-fast",
    displayName: "GPT-5.2 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-fast",
    wireId: "gpt-5.2-fast",
    displayName: "GPT-5.2 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-high",
    wireId: "gpt-5.2-high",
    displayName: "GPT-5.2 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-high-fast",
    wireId: "gpt-5.2-high-fast",
    displayName: "GPT-5.2 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-xhigh",
    wireId: "gpt-5.2-xhigh",
    displayName: "GPT-5.2 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.2-xhigh-fast",
    wireId: "gpt-5.2-xhigh-fast",
    displayName: "GPT-5.2 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-none",
    wireId: "gpt-5.6-luna-none",
    displayName: "GPT-5.6 Luna None",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-none-fast",
    wireId: "gpt-5.6-luna-none-fast",
    displayName: "GPT-5.6 Luna None Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-low",
    wireId: "gpt-5.6-luna-low",
    displayName: "GPT-5.6 Luna Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-low-fast",
    wireId: "gpt-5.6-luna-low-fast",
    displayName: "GPT-5.6 Luna Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-medium",
    wireId: "gpt-5.6-luna-medium",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-medium-fast",
    wireId: "gpt-5.6-luna-medium-fast",
    displayName: "GPT-5.6 Luna Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-high",
    wireId: "gpt-5.6-luna-high",
    displayName: "GPT-5.6 Luna High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-high-fast",
    wireId: "gpt-5.6-luna-high-fast",
    displayName: "GPT-5.6 Luna High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh",
    wireId: "gpt-5.6-luna-xhigh",
    displayName: "GPT-5.6 Luna Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh-fast",
    wireId: "gpt-5.6-luna-xhigh-fast",
    displayName: "GPT-5.6 Luna Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-max",
    wireId: "gpt-5.6-luna-max",
    displayName: "GPT-5.6 Luna Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna-max-fast",
    wireId: "gpt-5.6-luna-max-fast",
    displayName: "GPT-5.6 Luna Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.6-flash-minimal",
    wireId: "gemini-3.6-flash-minimal",
    displayName: "Gemini 3.6 Flash Minimal",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.6-flash-low",
    wireId: "gemini-3.6-flash-low",
    displayName: "Gemini 3.6 Flash Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.6-flash-medium",
    wireId: "gemini-3.6-flash-medium",
    displayName: "Gemini 3.6 Flash Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.6-flash-high",
    wireId: "gemini-3.6-flash-high",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.1-pro",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini-none",
    wireId: "gpt-5.4-mini-none",
    displayName: "GPT-5.4 Mini None",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini-low",
    wireId: "gpt-5.4-mini-low",
    displayName: "GPT-5.4 Mini Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
