/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-8-thinking-high",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-high-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-thinking-max",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-max-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-opus-4.8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4-8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-none",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-none-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-low",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-low-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-medium",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-medium-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-high",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-high-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-max",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-max-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol Context 272k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-latest",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-sol",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-none",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-none-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-low",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-low-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-medium",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-medium-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-high",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-high-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-extra-high",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-extra-high-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5 Context 272k Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-5",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-fable-5",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-low",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-medium",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-high",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-xhigh",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-max",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-low",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Thinking Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-medium",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Thinking Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-high",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-xhigh",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-max",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5 Thinking Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-fable-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-fable",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-fable-5",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
]
