/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4.5-opus-high-thinking",
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-opus-high-thinking",
    wireId: "claude-4.5-opus-high-thinking",
    displayName: "Claude Opus 4.5 Thinking",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-opus-4-5",
    runModelId: "claude-4.5-opus-high-thinking",
    parameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-opus-4.5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-opus-4-5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-opus-high",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-gpt-5.2",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "gpt-5.2",
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-low",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-low-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-high",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-high-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-xhigh",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-xhigh-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultRunModelId: "gpt-5.6-luna-medium",
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-medium",
    wireId: "gpt-5.6-luna-medium",
    displayName: "GPT-5.6 Luna Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    runModelId: "gpt-5.6-luna-medium",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-luna",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-none",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-none-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-low",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-low-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-medium-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-high",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-high-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-max",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-max-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gemini-3.6-flash",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    defaultRunModelId: "gemini-3.6-flash-high",
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-high",
    wireId: "gemini-3.6-flash-high",
    displayName: "Gemini 3.6 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gemini-3.6-flash",
    runModelId: "gemini-3.6-flash-high",
    parameterValues: [{ id: "effort", value: "high" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-minimal",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-low",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-medium",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.1-pro",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-3.1-pro",
  },
  {
    id: "cursor-gemini-latest",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-pro-latest",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-pro",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    defaultRunModelId: "gpt-5.4-mini-medium",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-medium",
    wireId: "gpt-5.4-mini-medium",
    displayName: "GPT-5.4 Mini Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gpt-5.4-mini",
    runModelId: "gpt-5.4-mini-medium",
    parameterValues: [{ id: "reasoning", value: "medium" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-mini-latest",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-mini",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-none",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-low",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-high",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-xhigh",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    defaultRunModelId: "gpt-5.4-nano-medium",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-medium",
    wireId: "gpt-5.4-nano-medium",
    displayName: "GPT-5.4 Nano Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gpt-5.4-nano",
    runModelId: "gpt-5.4-nano-medium",
    parameterValues: [{ id: "reasoning", value: "medium" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-nano-latest",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-nano",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-none",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-low",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-high",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-xhigh",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-claude-haiku-4-5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4.5-haiku-thinking",
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-haiku-thinking",
    wireId: "claude-4.5-haiku-thinking",
    displayName: "Claude Haiku 4.5 Thinking",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-haiku-4-5",
    runModelId: "claude-4.5-haiku-thinking",
    parameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-latest",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-4.5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-4-5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-haiku",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-sonnet-4-5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4.5-sonnet-thinking",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4.5-sonnet-thinking",
    wireId: "claude-4.5-sonnet-thinking",
    displayName: "Claude Sonnet 4.5 Thinking Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4-5",
    runModelId: "claude-4.5-sonnet-thinking",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-sonnet-4.5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
]
