/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-default",
    wireId: "default",
    displayName: "Auto",
    defaultOn: true,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-low",
    wireId: "cursor-grok-4.6-low",
    displayName: "Cursor Grok 4.6 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-low-fast",
    wireId: "cursor-grok-4.6-low-fast",
    displayName: "Cursor Grok 4.6 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-medium",
    wireId: "cursor-grok-4.6-medium",
    displayName: "Cursor Grok 4.6 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-medium-fast",
    wireId: "cursor-grok-4.6-medium-fast",
    displayName: "Cursor Grok 4.6 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-high",
    wireId: "cursor-grok-4.6-high",
    displayName: "Cursor Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-high-fast",
    wireId: "cursor-grok-4.6-high-fast",
    displayName: "Cursor Grok 4.6 Fast",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-xhigh",
    wireId: "cursor-grok-4.6-xhigh",
    displayName: "Cursor Grok 4.6 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6-xhigh-fast",
    wireId: "cursor-grok-4.6-xhigh-fast",
    displayName: "Cursor Grok 4.6 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-composer-2.5-fast",
    wireId: "composer-2.5-fast",
    displayName: "Composer 2.5 Fast",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-composer-2.5",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-low",
    wireId: "claude-opus-5-low",
    displayName: "Opus 5 Low",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-low-fast",
    wireId: "claude-opus-5-low-fast",
    displayName: "Opus 5 Low Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-medium",
    wireId: "claude-opus-5-medium",
    displayName: "Opus 5 Medium",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-medium-fast",
    wireId: "claude-opus-5-medium-fast",
    displayName: "Opus 5 Medium Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-high",
    wireId: "claude-opus-5-high",
    displayName: "Opus 5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-high-fast",
    wireId: "claude-opus-5-high-fast",
    displayName: "Opus 5 Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-low",
    wireId: "claude-opus-5-thinking-low",
    displayName: "Opus 5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-low-fast",
    wireId: "claude-opus-5-thinking-low-fast",
    displayName: "Opus 5 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-medium",
    wireId: "claude-opus-5-thinking-medium",
    displayName: "Opus 5 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-medium-fast",
    wireId: "claude-opus-5-thinking-medium-fast",
    displayName: "Opus 5 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-high",
    wireId: "claude-opus-5-thinking-high",
    displayName: "Opus 5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-high-fast",
    wireId: "claude-opus-5-thinking-high-fast",
    displayName: "Opus 5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh",
    wireId: "claude-opus-5-thinking-xhigh",
    displayName: "Opus 5 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh-fast",
    wireId: "claude-opus-5-thinking-xhigh-fast",
    displayName: "Opus 5 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-max",
    wireId: "claude-opus-5-thinking-max",
    displayName: "Opus 5 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5-thinking-max-fast",
    wireId: "claude-opus-5-thinking-max-fast",
    displayName: "Opus 5 Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-low",
    wireId: "claude-opus-4-8-low",
    displayName: "Opus 4.8 Low",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-low-fast",
    wireId: "claude-opus-4-8-low-fast",
    displayName: "Opus 4.8 Low Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-medium",
    wireId: "claude-opus-4-8-medium",
    displayName: "Opus 4.8 Medium",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-medium-fast",
    wireId: "claude-opus-4-8-medium-fast",
    displayName: "Opus 4.8 Medium Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-high",
    wireId: "claude-opus-4-8-high",
    displayName: "Opus 4.8",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-high-fast",
    wireId: "claude-opus-4-8-high-fast",
    displayName: "Opus 4.8 Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-xhigh",
    wireId: "claude-opus-4-8-xhigh",
    displayName: "Opus 4.8 Extra High",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-xhigh-fast",
    wireId: "claude-opus-4-8-xhigh-fast",
    displayName: "Opus 4.8 Extra High Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-max",
    wireId: "claude-opus-4-8-max",
    displayName: "Opus 4.8 Max",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-max-fast",
    wireId: "claude-opus-4-8-max-fast",
    displayName: "Opus 4.8 Max Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low",
    wireId: "claude-opus-4-8-thinking-low",
    displayName: "Opus 4.8 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low-fast",
    wireId: "claude-opus-4-8-thinking-low-fast",
    displayName: "Opus 4.8 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium",
    wireId: "claude-opus-4-8-thinking-medium",
    displayName: "Opus 4.8 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium-fast",
    wireId: "claude-opus-4-8-thinking-medium-fast",
    displayName: "Opus 4.8 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-high",
    wireId: "claude-opus-4-8-thinking-high",
    displayName: "Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-high-fast",
    wireId: "claude-opus-4-8-thinking-high-fast",
    displayName: "Opus 4.8 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh",
    wireId: "claude-opus-4-8-thinking-xhigh",
    displayName: "Opus 4.8 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh-fast",
    wireId: "claude-opus-4-8-thinking-xhigh-fast",
    displayName: "Opus 4.8 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
