/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-gpt-5.4-mini-none",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    parentWireId: "gpt-5.4-mini",
    parameterValues: [{ id: "reasoning", value: "none" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-low",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "gpt-5.4-mini",
    parameterValues: [{ id: "reasoning", value: "low" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-medium",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gpt-5.4-mini",
    parameterValues: [{ id: "reasoning", value: "medium" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-high",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gpt-5.4-mini",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-mini-xhigh",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "gpt-5.4-mini",
    parameterValues: [{ id: "reasoning", value: "xhigh" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-mini-latest",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-mini",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-none",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    parentWireId: "gpt-5.4-nano",
    parameterValues: [{ id: "reasoning", value: "none" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-low",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "gpt-5.4-nano",
    parameterValues: [{ id: "reasoning", value: "low" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-medium",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gpt-5.4-nano",
    parameterValues: [{ id: "reasoning", value: "medium" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-high",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gpt-5.4-nano",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.4-nano-xhigh",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "gpt-5.4-nano",
    parameterValues: [{ id: "reasoning", value: "xhigh" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-nano-latest",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-nano",
    wireId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-claude-haiku-4-5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-haiku",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-haiku-4-5",
    parameterValues: [{ id: "thinking", value: "false" }],
  },
  {
    id: "cursor-claude-4.5-haiku-thinking",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5 Thinking",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-haiku-4-5",
    parameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-latest",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-4.5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-haiku-4-5",
    wireId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-sonnet-4-5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4.5-sonnet",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5 Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4.5-sonnet-thinking",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5 Thinking Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-sonnet-4.5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-sonnet-4-5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-gpt-5.1",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.1-low",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "gpt-5.1",
    parameterValues: [{ id: "reasoning", value: "low" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.1-high",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gpt-5.1",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gemini-3-flash",
    wireId: "gemini-3-flash",
    displayName: "Gemini 3 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.5-flash",
    wireId: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-4",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4-sonnet",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4 Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4-sonnet-thinking",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4 Thinking Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-sonnet-4",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-gpt-5-mini",
    wireId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-2.5-flash",
    wireId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k3",
    wireId: "kimi-k3",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-low",
    wireId: "kimi-k3",
    displayName: "Kimi K3 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "kimi-k3",
    parameterValues: [{ id: "reasoning", value: "low" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-high",
    wireId: "kimi-k3",
    displayName: "Kimi K3 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "kimi-k3",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-max",
    wireId: "kimi-k3",
    displayName: "Kimi K3 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "kimi-k3",
    parameterValues: [{ id: "reasoning", value: "max" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k2.7-code",
    wireId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-latest",
    wireId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi",
    wireId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-glm-5.2",
    wireId: "glm-5.2",
    displayName: "GLM 5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high", "max"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5.2-high",
    wireId: "glm-5.2",
    displayName: "GLM 5.2 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "glm-5.2",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5.2-max",
    wireId: "glm-5.2",
    displayName: "GLM 5.2 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "glm-5.2",
    parameterValues: [{ id: "reasoning", value: "max" }],
    effortParamId: "reasoning",
  },
]
