/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-default",
    wireId: "default",
    displayName: "Auto",
    defaultOn: true,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-low",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-low-fast",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-medium",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-medium-fast",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-high",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-high-fast",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-xhigh",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-xhigh-fast",
    wireId: "grok-4.6",
    displayName: "Cursor Grok 4.6 Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "grok-4.6",
    parameterValues: [
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2.5",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2.5-fast",
    wireId: "composer-2.5",
    displayName: "Composer 2.5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    parentWireId: "composer-2.5",
    parameterValues: [{ id: "fast", value: "true" }],
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-latest",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-composer",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2-5",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-low",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-low-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-medium",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-medium-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-high",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-high-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-thinking-low",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-low-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-thinking-medium",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-medium-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-thinking-high",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-high-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-5-thinking-max",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-max-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5 Thinking Context 300k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-opus-latest",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-5",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-low",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-low-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-medium",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-medium-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-high",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-high-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-xhigh",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-xhigh-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-max",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-max-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Context 300k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8 Thinking Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
]
