/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-gpt-5.4-xhigh-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-low",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Context 200k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-medium",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Context 200k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-high",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Context 200k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-max",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Context 200k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-low-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Thinking Context 200k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-medium-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Thinking Context 200k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-high-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Thinking Context 200k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-opus-max-thinking",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6 Thinking Context 200k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-opus-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-opus-4.6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-opus-4-6",
    wireId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-opus-4-5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-claude-4.5-opus-high",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-opus-4-5",
    parameterValues: [{ id: "thinking", value: "false" }],
  },
  {
    id: "cursor-claude-4.5-opus-high-thinking",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5 Thinking",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-opus-4-5",
    parameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-opus-4.5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-opus-4-5",
    wireId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [{ id: "thinking", value: "true" }],
  },
  {
    id: "cursor-gpt-5.2",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-low",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-low-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-high",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-high-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-xhigh",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.2-xhigh-fast",
    wireId: "gpt-5.2",
    displayName: "GPT-5.2 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.2",
    parameterValues: [
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-none",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-none-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-low",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-low-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-medium",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-medium-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-high",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-high-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-xhigh-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-max",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-luna-max-fast",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna Context 272k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-luna",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-luna",
    wireId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gemini-3.6-flash",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-minimal",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash Minimal",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    parentWireId: "gemini-3.6-flash",
    parameterValues: [{ id: "effort", value: "minimal" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-low",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "gemini-3.6-flash",
    parameterValues: [{ id: "effort", value: "low" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-medium",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gemini-3.6-flash",
    parameterValues: [{ id: "effort", value: "medium" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.6-flash-high",
    wireId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gemini-3.6-flash",
    parameterValues: [{ id: "effort", value: "high" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.1-pro",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-latest",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-pro-latest",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-pro",
    wireId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini",
    wireId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh"],
    effortParamId: "reasoning",
  },
]
