/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-gpt-5.4-mini-medium",
    wireId: "gpt-5.4-mini-medium",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini-high",
    wireId: "gpt-5.4-mini-high",
    displayName: "GPT-5.4 Mini High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini-xhigh",
    wireId: "gpt-5.4-mini-xhigh",
    displayName: "GPT-5.4 Mini Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano-none",
    wireId: "gpt-5.4-nano-none",
    displayName: "GPT-5.4 Nano None",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano-low",
    wireId: "gpt-5.4-nano-low",
    displayName: "GPT-5.4 Nano Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano-medium",
    wireId: "gpt-5.4-nano-medium",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano-high",
    wireId: "gpt-5.4-nano-high",
    displayName: "GPT-5.4 Nano High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano-xhigh",
    wireId: "gpt-5.4-nano-xhigh",
    displayName: "GPT-5.4 Nano Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-haiku",
    wireId: "claude-4.5-haiku",
    displayName: "Haiku 4.5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-haiku-thinking",
    wireId: "claude-4.5-haiku-thinking",
    displayName: "Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-sonnet",
    wireId: "claude-4.5-sonnet",
    displayName: "Sonnet 4.5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.5-sonnet-thinking",
    wireId: "claude-4.5-sonnet-thinking",
    displayName: "Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.1-low",
    wireId: "gpt-5.1-low",
    displayName: "GPT-5.1 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.1",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.1-high",
    wireId: "gpt-5.1-high",
    displayName: "GPT-5.1 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3-flash",
    wireId: "gemini-3-flash",
    displayName: "Gemini 3 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.5-flash",
    wireId: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4-sonnet",
    wireId: "claude-4-sonnet",
    displayName: "Sonnet 4",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4-sonnet-thinking",
    wireId: "claude-4-sonnet-thinking",
    displayName: "Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5-mini",
    wireId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-2.5-flash",
    wireId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k3-low",
    wireId: "kimi-k3-low",
    displayName: "Kimi K3 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k3-high",
    wireId: "kimi-k3-high",
    displayName: "Kimi K3 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k3-max",
    wireId: "kimi-k3-max",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k2.7-code",
    wireId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-glm-5.2-high",
    wireId: "glm-5.2-high",
    displayName: "GLM 5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-glm-5.2-max",
    wireId: "glm-5.2-max",
    displayName: "GLM 5.2 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.6",
    wireId: "cursor-grok-4.6-high-fast",
    displayName: "Cursor Grok 4.6 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-5",
    wireId: "claude-opus-5-thinking-high",
    displayName: "Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8",
    wireId: "claude-opus-4-8-thinking-high",
    displayName: "Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol",
    wireId: "gpt-5.6-sol-medium",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5",
    wireId: "gpt-5.5-medium",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5",
    wireId: "claude-fable-5-thinking-high",
    displayName: "Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-fast-medium",
    wireId: "cursor-grok-4.5-low-fast",
    displayName: "Cursor Grok 4.5 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-fast-high",
    wireId: "cursor-grok-4.5-medium-fast",
    displayName: "Cursor Grok 4.5 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-xhigh",
    wireId: "cursor-grok-4.5-high",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5",
    wireId: "cursor-grok-4.5-high-fast",
    displayName: "Cursor Grok 4.5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-fast-xhigh",
    wireId: "cursor-grok-4.5-high-fast",
    displayName: "Cursor Grok 4.5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.7-flash",
    wireId: "gemini-3.7-flash-high",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra",
    wireId: "gpt-5.6-terra-medium",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5",
    wireId: "claude-sonnet-5-thinking-high",
    displayName: "Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-4-6",
    wireId: "claude-4.6-sonnet-medium-thinking",
    displayName: "Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7",
    wireId: "claude-opus-4-7-thinking-xhigh",
    displayName: "Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4",
    wireId: "gpt-5.4-medium",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-6",
    wireId: "claude-4.6-opus-high-thinking",
    displayName: "Opus 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
