/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-fable-5-thinking-max",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-grok-4.5",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "cursor-grok-4.5-high-fast",
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-high-fast",
    wireId: "cursor-grok-4.5-high-fast",
    displayName: "Grok 4.5 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.5",
    runModelId: "cursor-grok-4.5-high-fast",
    parameterValues: [
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-low",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-low-fast",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-medium",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-medium-fast",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-high",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-medium",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-high",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-xhigh",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-xhigh",
    wireId: "grok-4.5",
    displayName: "Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gemini-3.8-flash",
    wireId: "gemini-3.8-flash",
    displayName: "Gemini 3.8 Flash",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    defaultRunModelId: "gemini-3.8-flash-high",
    effortParamId: "Effort",
  },
  {
    id: "cursor-gemini-3.8-flash-high",
    wireId: "gemini-3.8-flash-high",
    displayName: "Gemini 3.8 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gemini-3.8-flash",
    runModelId: "gemini-3.8-flash-high",
    parameterValues: [{ id: "reasoning_effort", value: "high" }],
    effortParamId: "Effort",
  },
  {
    id: "cursor-gemini-3.7-flash",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    defaultRunModelId: "gemini-3.7-flash-high",
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-high",
    wireId: "gemini-3.7-flash-high",
    displayName: "Gemini 3.7 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gemini-3.7-flash",
    runModelId: "gemini-3.7-flash-high",
    parameterValues: [{ id: "effort", value: "high" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-flash-latest",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-flash",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-low",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-medium",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["minimal", "low", "medium", "high", "xhigh", "max"],
    defaultRunModelId: "muse-spark-1.3-high",
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-high",
    wireId: "muse-spark-1.3-high",
    displayName: "Muse Spark 1.3 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "muse-spark-1.3",
    runModelId: "muse-spark-1.3-high",
    parameterValues: [
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["minimal", "low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["minimal", "low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-minimal",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["minimal", "low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-low",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-medium",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-xhigh",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-muse-spark-1.3-max",
    wireId: "muse-spark-1.3",
    displayName: "Muse Spark 1.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gpt-5.6-terra",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultRunModelId: "gpt-5.6-terra-medium",
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-medium",
    wireId: "gpt-5.6-terra-medium",
    displayName: "GPT-5.6 Terra Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    runModelId: "gpt-5.6-terra-medium",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-terra",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-none",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-none-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-low",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-low-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-medium-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-high",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-high-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-max",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-max-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-sonnet-5-5",
    wireId: "claude-sonnet-5-5",
    displayName: "Claude Sonnet 5.5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultRunModelId: "claude-sonnet-5-5-high",
    defaultParameterValues: [{ id: "context", value: "300k" }],
    effortParamId: "Effort",
  },
  {
    id: "cursor-claude-sonnet-5-5-high",
    wireId: "claude-sonnet-5-5-high",
    displayName: "Claude Sonnet 5.5 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-5-5",
    runModelId: "claude-sonnet-5-5-high",
    parameterValues: [
      { id: "context", value: "300k" },
      { id: "reasoning_effort", value: "high" },
    ],
    effortParamId: "Effort",
  },
  {
    id: "cursor-claude-sonnet-5",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultRunModelId: "claude-sonnet-5-thinking-high",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-high",
    wireId: "claude-sonnet-5-thinking-high",
    displayName: "Claude Sonnet 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-5",
    runModelId: "claude-sonnet-5-thinking-high",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-latest",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-5",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-low",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-medium",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-high",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-xhigh",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-max",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-low",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-medium",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-xhigh",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-max",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-4-6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultRunModelId: "claude-4.6-sonnet-medium-thinking",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-medium-thinking",
    wireId: "claude-4.6-sonnet-medium-thinking",
    displayName: "Claude Sonnet 4.6 Thinking Context 200k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-sonnet-4-6",
    runModelId: "claude-4.6-sonnet-medium-thinking",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-4.6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-4-6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
]
