/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-grok-4.5",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-low",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-low-fast",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-medium",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-medium-fast",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-high",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-high-fast",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.5",
    parameterValues: [
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-medium",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-high",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-xhigh",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.5-fast-xhigh",
    wireId: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gemini-3.7-flash",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-low",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "gemini-3.7-flash",
    parameterValues: [{ id: "effort", value: "low" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-medium",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "gemini-3.7-flash",
    parameterValues: [{ id: "effort", value: "medium" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-3.7-flash-high",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "gemini-3.7-flash",
    parameterValues: [{ id: "effort", value: "high" }],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-flash-latest",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gemini-flash",
    wireId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "effort",
  },
  {
    id: "cursor-gpt-5.6-terra",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-none",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-none-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-low",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-low-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-medium",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-medium-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-high",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-high-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-max",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-terra-max-fast",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra Context 272k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "gpt-5.6-terra",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-terra",
    wireId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-sonnet-5",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-low",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-medium",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-high",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-xhigh",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-max",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-low",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Thinking Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-medium",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Thinking Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-high",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-xhigh",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-5-thinking-max",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5 Thinking Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-sonnet-5",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-latest",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-5",
    wireId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-sonnet-4-6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-low",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Context 200k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-medium",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Context 200k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-high",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Context 200k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-max",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Context 200k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-low-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Thinking Context 200k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "low" },
    ],
    effortParamId: "effort",
  },
]
