/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-8-thinking-max",
    wireId: "claude-opus-4-8-thinking-max",
    displayName: "Opus 4.8 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-8-thinking-max-fast",
    wireId: "claude-opus-4-8-thinking-max-fast",
    displayName: "Opus 4.8 Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-none",
    wireId: "gpt-5.6-sol-none",
    displayName: "GPT-5.6 Sol None",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-none-fast",
    wireId: "gpt-5.6-sol-none-fast",
    displayName: "GPT-5.6 Sol None Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-low",
    wireId: "gpt-5.6-sol-low",
    displayName: "GPT-5.6 Sol Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-low-fast",
    wireId: "gpt-5.6-sol-low-fast",
    displayName: "GPT-5.6 Sol Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-medium",
    wireId: "gpt-5.6-sol-medium",
    displayName: "GPT-5.6 Sol",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-medium-fast",
    wireId: "gpt-5.6-sol-medium-fast",
    displayName: "GPT-5.6 Sol Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-high",
    wireId: "gpt-5.6-sol-high",
    displayName: "GPT-5.6 Sol High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-high-fast",
    wireId: "gpt-5.6-sol-high-fast",
    displayName: "GPT-5.6 Sol High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh",
    wireId: "gpt-5.6-sol-xhigh",
    displayName: "GPT-5.6 Sol Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh-fast",
    wireId: "gpt-5.6-sol-xhigh-fast",
    displayName: "GPT-5.6 Sol Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-max",
    wireId: "gpt-5.6-sol-max",
    displayName: "GPT-5.6 Sol Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-sol-max-fast",
    wireId: "gpt-5.6-sol-max-fast",
    displayName: "GPT-5.6 Sol Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-none",
    wireId: "gpt-5.5-none",
    displayName: "GPT-5.5 None",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-none-fast",
    wireId: "gpt-5.5-none-fast",
    displayName: "GPT-5.5 None Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-low",
    wireId: "gpt-5.5-low",
    displayName: "GPT-5.5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-low-fast",
    wireId: "gpt-5.5-low-fast",
    displayName: "GPT-5.5 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-medium",
    wireId: "gpt-5.5-medium",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-medium-fast",
    wireId: "gpt-5.5-medium-fast",
    displayName: "GPT-5.5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-high",
    wireId: "gpt-5.5-high",
    displayName: "GPT-5.5 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-high-fast",
    wireId: "gpt-5.5-high-fast",
    displayName: "GPT-5.5 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-extra-high",
    wireId: "gpt-5.5-extra-high",
    displayName: "GPT-5.5 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.5-extra-high-fast",
    wireId: "gpt-5.5-extra-high-fast",
    displayName: "GPT-5.5 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-low",
    wireId: "claude-fable-5-low",
    displayName: "Fable 5 Low",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-medium",
    wireId: "claude-fable-5-medium",
    displayName: "Fable 5 Medium",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-high",
    wireId: "claude-fable-5-high",
    displayName: "Fable 5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-xhigh",
    wireId: "claude-fable-5-xhigh",
    displayName: "Fable 5 Extra High",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-max",
    wireId: "claude-fable-5-max",
    displayName: "Fable 5 Max",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-thinking-low",
    wireId: "claude-fable-5-thinking-low",
    displayName: "Fable 5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-thinking-medium",
    wireId: "claude-fable-5-thinking-medium",
    displayName: "Fable 5 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-thinking-high",
    wireId: "claude-fable-5-thinking-high",
    displayName: "Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-thinking-xhigh",
    wireId: "claude-fable-5-thinking-xhigh",
    displayName: "Fable 5 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-fable-5-thinking-max",
    wireId: "claude-fable-5-thinking-max",
    displayName: "Fable 5 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-low",
    wireId: "cursor-grok-4.5-low",
    displayName: "Cursor Grok 4.5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-low-fast",
    wireId: "cursor-grok-4.5-low-fast",
    displayName: "Cursor Grok 4.5 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-medium",
    wireId: "cursor-grok-4.5-medium",
    displayName: "Cursor Grok 4.5 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-medium-fast",
    wireId: "cursor-grok-4.5-medium-fast",
    displayName: "Cursor Grok 4.5 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-high",
    wireId: "cursor-grok-4.5-high",
    displayName: "Cursor Grok 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-grok-4.5-high-fast",
    wireId: "cursor-grok-4.5-high-fast",
    displayName: "Cursor Grok 4.5 Fast",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.7-flash-low",
    wireId: "gemini-3.7-flash-low",
    displayName: "Gemini 3.7 Flash Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.7-flash-medium",
    wireId: "gemini-3.7-flash-medium",
    displayName: "Gemini 3.7 Flash Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.7-flash-high",
    wireId: "gemini-3.7-flash-high",
    displayName: "Gemini 3.7 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-none",
    wireId: "gpt-5.6-terra-none",
    displayName: "GPT-5.6 Terra None",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-none-fast",
    wireId: "gpt-5.6-terra-none-fast",
    displayName: "GPT-5.6 Terra None Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
