/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-8-max-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-low-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-medium-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-high-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-xhigh-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-max",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-max-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultRunModelId: "gpt-5.6-sol-medium",
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-medium",
    wireId: "gpt-5.6-sol-medium",
    displayName: "GPT-5.6 Sol Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.6-sol",
    runModelId: "gpt-5.6-sol-medium",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-latest",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-6-sol",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-none",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-none-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-low",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-low-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-medium-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-high",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-high-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-xhigh-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-max",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.6-sol-max-fast",
    wireId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "gpt-5.5-medium",
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-medium",
    wireId: "gpt-5.5-medium",
    displayName: "GPT-5.5 Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.5",
    runModelId: "gpt-5.5-medium",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5-5",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-none",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-none-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-low",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-low-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-medium-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-high",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-high-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-extra-high",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.5-extra-high-fast",
    wireId: "gpt-5.5",
    displayName: "GPT-5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-fable-5-1",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultRunModelId: "claude-fable-5-1-thinking-high",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-thinking-high",
    wireId: "claude-fable-5-1-thinking-high",
    displayName: "Claude Fable 5.1 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-fable-5-1",
    runModelId: "claude-fable-5-1-thinking-high",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-fable-5-1",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-low",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-medium",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-high",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-xhigh",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-max",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-thinking-low",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-thinking-medium",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-thinking-xhigh",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-1-thinking-max",
    wireId: "claude-fable-5-1",
    displayName: "Claude Fable 5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultRunModelId: "claude-fable-5-thinking-high",
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-high",
    wireId: "claude-fable-5-thinking-high",
    displayName: "Claude Fable 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-fable-5",
    runModelId: "claude-fable-5-thinking-high",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-fable",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-fable-5",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-low",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-medium",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-high",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-xhigh",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-max",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-low",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-medium",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-fable-5-thinking-xhigh",
    wireId: "claude-fable-5",
    displayName: "Claude Fable 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
  },
]
