/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-4.6-sonnet-medium-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Thinking Context 200k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "medium" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-high-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Thinking Context 200k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "high" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-claude-4.6-sonnet-max-thinking",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Thinking Context 200k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "claude-sonnet-4-6",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
      { id: "effort", value: "max" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-4.6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-sonnet-4-6",
    wireId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "max"],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
    effortParamId: "effort",
  },
  {
    id: "cursor-gpt-5.3-codex",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-low",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-low-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-high",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-high-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh-fast",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.3-codex",
    parameterValues: [
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex-latest",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-codex-5.3",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-low",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-low-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-medium",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-medium-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-high",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-high-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-xhigh",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-xhigh-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-max",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-max-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Context 300k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-thinking-high",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-high-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Xhigh",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-xhigh-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Xhigh Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["xhigh"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "xhigh" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-7-thinking-max-fast",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7 Thinking Context 300k Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    speedFast: true,
    parentWireId: "claude-opus-4-7",
    parameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
      { id: "effort", value: "max" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
    maxMode: true,
  },
  {
    id: "cursor-opus-4.7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4-7",
    wireId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high", "xhigh", "max"],
    speedFast: true,
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "300k" },
    ],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultParameterValues: [{ id: "context", value: "272k" }],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-none",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-none-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "none" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-low",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-low-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "low" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-medium",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-medium-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "medium" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-high",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-high-fast",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "high" },
      { id: "fast", value: "true" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
  {
    id: "cursor-gpt-5.4-xhigh",
    wireId: "gpt-5.4",
    displayName: "GPT-5.4 Context 272k Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    parentWireId: "gpt-5.4",
    parameterValues: [
      { id: "context", value: "272k" },
      { id: "reasoning", value: "extra-high" },
      { id: "fast", value: "false" },
    ],
    effortParamId: "reasoning",
    fastParamId: "fast",
  },
]
