/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-gpt-5.6-terra-low",
    wireId: "gpt-5.6-terra-low",
    displayName: "GPT-5.6 Terra Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-low-fast",
    wireId: "gpt-5.6-terra-low-fast",
    displayName: "GPT-5.6 Terra Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-medium",
    wireId: "gpt-5.6-terra-medium",
    displayName: "GPT-5.6 Terra",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-medium-fast",
    wireId: "gpt-5.6-terra-medium-fast",
    displayName: "GPT-5.6 Terra Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-high",
    wireId: "gpt-5.6-terra-high",
    displayName: "GPT-5.6 Terra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-high-fast",
    wireId: "gpt-5.6-terra-high-fast",
    displayName: "GPT-5.6 Terra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh",
    wireId: "gpt-5.6-terra-xhigh",
    displayName: "GPT-5.6 Terra Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-xhigh-fast",
    wireId: "gpt-5.6-terra-xhigh-fast",
    displayName: "GPT-5.6 Terra Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-max",
    wireId: "gpt-5.6-terra-max",
    displayName: "GPT-5.6 Terra Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-terra-max-fast",
    wireId: "gpt-5.6-terra-max-fast",
    displayName: "GPT-5.6 Terra Max Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-low",
    wireId: "claude-sonnet-5-low",
    displayName: "Sonnet 5 Low",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-medium",
    wireId: "claude-sonnet-5-medium",
    displayName: "Sonnet 5 Medium",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-high",
    wireId: "claude-sonnet-5-high",
    displayName: "Sonnet 5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-xhigh",
    wireId: "claude-sonnet-5-xhigh",
    displayName: "Sonnet 5 Extra High",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-max",
    wireId: "claude-sonnet-5-max",
    displayName: "Sonnet 5 Max",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-thinking-low",
    wireId: "claude-sonnet-5-thinking-low",
    displayName: "Sonnet 5 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-thinking-medium",
    wireId: "claude-sonnet-5-thinking-medium",
    displayName: "Sonnet 5 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-thinking-high",
    wireId: "claude-sonnet-5-thinking-high",
    displayName: "Sonnet 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-thinking-xhigh",
    wireId: "claude-sonnet-5-thinking-xhigh",
    displayName: "Sonnet 5 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-5-thinking-max",
    wireId: "claude-sonnet-5-thinking-max",
    displayName: "Sonnet 5 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-sonnet-medium",
    wireId: "claude-4.6-sonnet-medium",
    displayName: "Sonnet 4.6",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-4.6-sonnet-medium-thinking",
    wireId: "claude-4.6-sonnet-medium-thinking",
    displayName: "Sonnet 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-low",
    wireId: "gpt-5.3-codex-low",
    displayName: "Codex 5.3 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-low-fast",
    wireId: "gpt-5.3-codex-low-fast",
    displayName: "Codex 5.3 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex",
    wireId: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-fast",
    wireId: "gpt-5.3-codex-fast",
    displayName: "Codex 5.3 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-high",
    wireId: "gpt-5.3-codex-high",
    displayName: "Codex 5.3 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-high-fast",
    wireId: "gpt-5.3-codex-high-fast",
    displayName: "Codex 5.3 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh",
    wireId: "gpt-5.3-codex-xhigh",
    displayName: "Codex 5.3 Extra High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.3-codex-xhigh-fast",
    wireId: "gpt-5.3-codex-xhigh-fast",
    displayName: "Codex 5.3 Extra High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-low",
    wireId: "claude-opus-4-7-low",
    displayName: "Opus 4.7 Low",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-low-fast",
    wireId: "claude-opus-4-7-low-fast",
    displayName: "Opus 4.7 Low Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-medium",
    wireId: "claude-opus-4-7-medium",
    displayName: "Opus 4.7 Medium",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-medium-fast",
    wireId: "claude-opus-4-7-medium-fast",
    displayName: "Opus 4.7 Medium Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-high",
    wireId: "claude-opus-4-7-high",
    displayName: "Opus 4.7 High",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-high-fast",
    wireId: "claude-opus-4-7-high-fast",
    displayName: "Opus 4.7 High Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-xhigh",
    wireId: "claude-opus-4-7-xhigh",
    displayName: "Opus 4.7",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-xhigh-fast",
    wireId: "claude-opus-4-7-xhigh-fast",
    displayName: "Opus 4.7 Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-max",
    wireId: "claude-opus-4-7-max",
    displayName: "Opus 4.7 Max",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-max-fast",
    wireId: "claude-opus-4-7-max-fast",
    displayName: "Opus 4.7 Max Fast",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low",
    wireId: "claude-opus-4-7-thinking-low",
    displayName: "Opus 4.7 Low",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-low-fast",
    wireId: "claude-opus-4-7-thinking-low-fast",
    displayName: "Opus 4.7 Low Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium",
    wireId: "claude-opus-4-7-thinking-medium",
    displayName: "Opus 4.7 Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-medium-fast",
    wireId: "claude-opus-4-7-thinking-medium-fast",
    displayName: "Opus 4.7 Medium Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-opus-4-7-thinking-high",
    wireId: "claude-opus-4-7-thinking-high",
    displayName: "Opus 4.7 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
