/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-claude-opus-4-5",
    wireId: "claude-4.5-opus-high-thinking",
    displayName: "Opus 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.6-luna",
    wireId: "gpt-5.6-luna-medium",
    displayName: "GPT-5.6 Luna",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gemini-3.6-flash",
    wireId: "gemini-3.6-flash-high",
    displayName: "Gemini 3.6 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-mini",
    wireId: "gpt-5.4-mini-medium",
    displayName: "GPT-5.4 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-gpt-5.4-nano",
    wireId: "gpt-5.4-nano-medium",
    displayName: "GPT-5.4 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-haiku-4-5",
    wireId: "claude-4.5-haiku-thinking",
    displayName: "Haiku 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-4-5",
    wireId: "claude-4.5-sonnet-thinking",
    displayName: "Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-claude-sonnet-4",
    wireId: "claude-4-sonnet",
    displayName: "Sonnet 4",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-kimi-k3",
    wireId: "kimi-k3-max",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
  {
    id: "cursor-glm-5.2",
    wireId: "glm-5.2-high",
    displayName: "GLM 5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
  },
]
