/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-default",
    wireId: "default",
    displayName: "Auto",
    defaultOn: true,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "default",
  },
  {
    id: "cursor-grok-4.7",
    wireId: "grok-4.7",
    displayName: "Grok 4.7",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    defaultRunModelId: "grok-4.7-high-fast",
    defaultParameterValues: [{"id":"context","value":"256k"}],
    effortParamId: "Effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.7-high-fast",
    wireId: "grok-4.7-high-fast",
    displayName: "Grok 4.7 Context 256k High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.7",
    runModelId: "grok-4.7-high-fast",
    parameterValues: [{"id":"context","value":"256k"},{"id":"reasoning_effort","value":"high"},{"id":"fast","value":"true"}],
    effortParamId: "Effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    defaultRunModelId: "cursor-grok-4.6-high-fast",
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-high-fast",
    wireId: "cursor-grok-4.6-high-fast",
    displayName: "Grok 4.6 High Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "grok-4.6",
    runModelId: "cursor-grok-4.6-high-fast",
    parameterValues: [{"id":"effort","value":"high"},{"id":"fast","value":"true"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-low",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-low-fast",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-medium",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-medium-fast",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-high",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-xhigh",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-grok-4.6-xhigh-fast",
    wireId: "grok-4.6",
    displayName: "Grok 4.6",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh"],
    speedFast: true,
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2.5",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    defaultRunModelId: "composer-2.5-fast",
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2.5-fast",
    wireId: "composer-2.5-fast",
    displayName: "Composer 2.5 Fast",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    parentWireId: "composer-2.5",
    runModelId: "composer-2.5-fast",
    parameterValues: [{"id":"fast","value":"true"}],
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-latest",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-composer",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-composer-2-5",
    wireId: "composer-2.5",
    displayName: "Composer 2.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultRunModelId: "claude-opus-5-5-medium",
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-medium",
    wireId: "claude-opus-5-5-medium",
    displayName: "Claude Opus 5.5 Context 300k Medium",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["medium"],
    speedFast: true,
    parentWireId: "claude-opus-5-5",
    runModelId: "claude-opus-5-5-medium",
    parameterValues: [{"id":"context","value":"300k"},{"id":"effort","value":"medium"},{"id":"fast","value":"false"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-latest",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-5.5",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-5-5",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-low",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-low-fast",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-medium-fast",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-high",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-high-fast",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-xhigh",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-xhigh-fast",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-max",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-5-max-fast",
    wireId: "claude-opus-5-5",
    displayName: "Claude Opus 5.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: true,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultRunModelId: "claude-opus-5-thinking-high",
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-high",
    wireId: "claude-opus-5-thinking-high",
    displayName: "Claude Opus 5 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-5",
    runModelId: "claude-opus-5-thinking-high",
    parameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"},{"id":"effort","value":"high"},{"id":"fast","value":"false"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-5",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-low",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-low-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-medium",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-medium-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-high",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-high-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-low",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-low-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-medium",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-medium-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-high-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-xhigh-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-max",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-5-thinking-max-fast",
    wireId: "claude-opus-5",
    displayName: "Claude Opus 5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultRunModelId: "claude-opus-4-8-thinking-high",
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-thinking-high",
    wireId: "claude-opus-4-8-thinking-high",
    displayName: "Claude Opus 4.8 Thinking Context 300k High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    speedFast: true,
    parentWireId: "claude-opus-4-8",
    runModelId: "claude-opus-4-8-thinking-high",
    parameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"},{"id":"effort","value":"high"},{"id":"fast","value":"false"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4.8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-opus-4-8",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-low",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-low-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-medium",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-medium-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-high",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-high-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-xhigh",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-xhigh-fast",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  },
  {
    id: "cursor-claude-opus-4-8-max",
    wireId: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 300000,
    maxOutputTokens: 16384,
    effortLevels: ["low","medium","high","xhigh","max"],
    speedFast: true,
    defaultParameterValues: [{"id":"thinking","value":"true"},{"id":"context","value":"300k"}],
    effortParamId: "effort",
    fastParamId: "fast",
  }
]
