/** Generated from authenticated Cursor AvailableModels; do not hand edit. */
import type { CursorStaticCatalogRow } from "./static-catalog-row.ts"

export const CURSOR_STATIC_CATALOG_PART: readonly CursorStaticCatalogRow[] = [
  {
    id: "cursor-sonnet-4-5",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4.5-sonnet",
    wireId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "true" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-gpt-5.1",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    defaultRunModelId: "gpt-5.1",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.1-low",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gpt-5.1-high",
    wireId: "gpt-5.1",
    displayName: "GPT-5.1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-gemini-3-flash",
    wireId: "gemini-3-flash",
    displayName: "Gemini 3 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-3-flash",
  },
  {
    id: "cursor-gemini-3.5-flash",
    wireId: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-3.5-flash",
  },
  {
    id: "cursor-claude-sonnet-4",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4-sonnet",
    defaultParameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4-sonnet",
    wireId: "claude-4-sonnet",
    displayName: "Claude Sonnet 4 Context 200k",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-sonnet-4",
    runModelId: "claude-4-sonnet",
    parameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-sonnet-4",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-claude-4-sonnet-thinking",
    wireId: "claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultParameterValues: [
      { id: "thinking", value: "false" },
      { id: "context", value: "200k" },
    ],
  },
  {
    id: "cursor-gpt-5-mini",
    wireId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-5-mini",
  },
  {
    id: "cursor-gpt-5-nano",
    wireId: "gpt-5-nano",
    displayName: "GPT-5 Nano",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-5-nano",
    isHidden: true,
  },
  {
    id: "cursor-gemini-2.5-flash",
    wireId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-2.5-flash",
  },
  {
    id: "cursor-kimi-k3",
    wireId: "kimi-k3",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    defaultRunModelId: "kimi-k3-max",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-max",
    wireId: "kimi-k3-max",
    displayName: "Kimi K3 Max",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    effortLevels: ["max"],
    parentWireId: "kimi-k3",
    runModelId: "kimi-k3-max",
    parameterValues: [{ id: "reasoning", value: "max" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-low",
    wireId: "kimi-k3",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k3-high",
    wireId: "kimi-k3",
    displayName: "Kimi K3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-kimi-k2.7-code",
    wireId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: false,
    contextWindow: 262000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "kimi-k2.7-code",
  },
  {
    id: "cursor-glm-5.2",
    wireId: "glm-5.2",
    displayName: "GLM 5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high", "max"],
    defaultRunModelId: "glm-5.2-high",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5.2-high",
    wireId: "glm-5.2-high",
    displayName: "GLM 5.2 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "glm-5.2",
    runModelId: "glm-5.2-high",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5.2-max",
    wireId: "glm-5.2",
    displayName: "GLM 5.2",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high", "max"],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-claude-4-opus",
    wireId: "claude-4-opus",
    displayName: "Claude Opus 4",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4-opus-thinking",
    defaultParameterValues: [{ id: "thinking", value: "true" }],
    isHidden: true,
  },
  {
    id: "cursor-claude-4-opus-thinking",
    wireId: "claude-4-opus-thinking",
    displayName: "Claude Opus 4 Thinking",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-4-opus",
    runModelId: "claude-4-opus-thinking",
    parameterValues: [{ id: "thinking", value: "true" }],
    isHidden: true,
  },
  {
    id: "cursor-claude-4.1-opus",
    wireId: "claude-4.1-opus",
    displayName: "Claude 4.1 Opus",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-4.1-opus-thinking",
    defaultParameterValues: [{ id: "thinking", value: "true" }],
    isHidden: true,
  },
  {
    id: "cursor-claude-4.1-opus-thinking",
    wireId: "claude-4.1-opus-thinking",
    displayName: "Claude 4.1 Opus Thinking",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    parentWireId: "claude-4.1-opus",
    runModelId: "claude-4.1-opus-thinking",
    parameterValues: [{ id: "thinking", value: "true" }],
    isHidden: true,
  },
  {
    id: "cursor-claude-3-opus",
    wireId: "claude-3-opus",
    displayName: "Claude 3 Opus",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-3-opus",
    isHidden: true,
  },
  {
    id: "cursor-claude-3-sonnet-200k",
    wireId: "claude-3-sonnet-200k",
    displayName: "Claude 3 Sonnet",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-3-sonnet-200k",
    isHidden: true,
  },
  {
    id: "cursor-claude-3-haiku-200k",
    wireId: "claude-3-haiku-200k",
    displayName: "Claude 3 Haiku",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "claude-3-haiku-200k",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-codex",
    wireId: "gpt-5-codex",
    displayName: "GPT-5 Codex",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    defaultRunModelId: "gpt-5-codex",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-codex-fast",
    wireId: "gpt-5-codex",
    displayName: "GPT-5 Codex",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5.1-codex",
    wireId: "gpt-5.1-codex",
    displayName: "GPT-5.1 Codex",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    defaultRunModelId: "gpt-5.1-codex",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5.1-codex-fast",
    wireId: "gpt-5.1-codex",
    displayName: "GPT-5.1 Codex",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    speedFast: true,
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-pro",
    wireId: "gpt-5-pro",
    displayName: "GPT-5 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-5-pro",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    defaultRunModelId: "gpt-5",
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-low",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-low-fast",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-fast",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-high",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-5-high-fast",
    wireId: "gpt-5",
    displayName: "GPT-5",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 272000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "medium", "high"],
    speedFast: true,
    effortParamId: "reasoning",
    fastParamId: "fast",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4.1",
    wireId: "gpt-4.1",
    displayName: "GPT-4.1",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4.1",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4.1-mini",
    wireId: "gpt-4.1-mini",
    displayName: "GPT-4.1 mini",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4.1-mini",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4.1-nano",
    wireId: "gpt-4.1-nano",
    displayName: "GPT-4.1 nano",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4.1-nano",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4",
    wireId: "gpt-4",
    displayName: "GPT-4",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 8192,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4-turbo",
    wireId: "gpt-4-turbo",
    displayName: "GPT-4 Turbo",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4-turbo",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4.5",
    wireId: "gpt-4.5",
    displayName: "GPT-4.5",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4.5",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4o",
    wireId: "gpt-4o",
    displayName: "GPT-4o",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4o",
    isHidden: true,
  },
  {
    id: "cursor-gpt-4o-mini",
    wireId: "gpt-4o-mini",
    displayName: "GPT-4o Mini",
    defaultOn: false,
    supportsThinking: false,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gpt-4o-mini",
    isHidden: true,
  },
  {
    id: "cursor-o1-mini",
    wireId: "o1-mini",
    displayName: "o1 mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o1-mini",
    isHidden: true,
  },
  {
    id: "cursor-o1",
    wireId: "o1",
    displayName: "o1",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o1",
    isHidden: true,
  },
  {
    id: "cursor-o3",
    wireId: "o3",
    displayName: "o3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o3",
    isHidden: true,
  },
  {
    id: "cursor-o3-mini",
    wireId: "o3-mini",
    displayName: "o3 mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o3-mini",
    isHidden: true,
  },
  {
    id: "cursor-o3-pro",
    wireId: "o3-pro",
    displayName: "o3 pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o3-pro",
    isHidden: true,
  },
  {
    id: "cursor-o4-mini",
    wireId: "o4-mini",
    displayName: "o4 mini",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "o4-mini",
    isHidden: true,
  },
  {
    id: "cursor-gemini-2.5-flash-lite",
    wireId: "gemini-2.5-flash-lite",
    displayName: "Gemini 2.5 Flash Lite",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-2.5-flash-lite",
    isHidden: true,
  },
  {
    id: "cursor-gemini-2.5-pro",
    wireId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: [],
    defaultRunModelId: "gemini-2.5-pro",
    isHidden: true,
  },
  {
    id: "cursor-glm-5p3",
    wireId: "glm-5p3",
    displayName: "GLM 5.3",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    defaultRunModelId: "glm-5p3-high",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5p3-high",
    wireId: "glm-5p3-high",
    displayName: "GLM 5.3 High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "glm-5p3",
    runModelId: "glm-5p3-high",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5p3-flash",
    wireId: "glm-5p3-flash",
    displayName: "GLM 5.3 Flash",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["low", "high", "max"],
    defaultRunModelId: "glm-5p3-flash-high",
    effortParamId: "reasoning",
  },
  {
    id: "cursor-glm-5p3-flash-high",
    wireId: "glm-5p3-flash-high",
    displayName: "GLM 5.3 Flash High",
    defaultOn: false,
    supportsThinking: true,
    supportsImages: true,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    effortLevels: ["high"],
    parentWireId: "glm-5p3-flash",
    runModelId: "glm-5p3-flash-high",
    parameterValues: [{ id: "reasoning", value: "high" }],
    effortParamId: "reasoning",
  },
]
